src/main/java/com/gnomon/epsos/model/Country.java
package com.gnomon.epsos.model;

public class Country {

	private String name;
	private String code;
	
	
	public Country(String name, String code) {
		this.name = name;
		this.code = code;
		
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

}

src/main/java/com/gnomon/epsos/model/Diagnoses.java
package com.gnomon.epsos.model;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.event.ActionEvent;

/**
 * A list of current session stored diagnoses.
 *
 * @author Akis Papadopoulos
 */
@ManagedBean(name = "diagnoses")
@SessionScoped
public class Diagnoses {

    //Current stored diagnoses
    private List<Diagnosis> list = new ArrayList<Diagnosis>();
    //Current selected diagnosis
    private Diagnosis selectedDiagnosis;

    /**
     * A method returning the selected diagnosis.
     *
     * @return the selected diagnosis.
     */
    public Diagnosis getSelectedDiagnosis() {
        return selectedDiagnosis;
    }

    /**
     * A method setting the selected diagnosis.
     *
     * @param diagnosis the selected diagnosis.
     */
    public void setSelectedDiagnosis(Diagnosis diagnosis) {
        this.selectedDiagnosis = diagnosis;
    }

    /**
     * A method adding a diagnosis into the list of diagnoses.
     *
     * @param diagnosis a diagnosis.
     */
    public void add(Diagnosis diagnosis) {
        list.add(diagnosis);
    }

    /**
     * A method returning the list of current stored diagnoses.
     *
     * @return the list of current stored diagnoses.
     */
    public List<Diagnosis> getList() {
        return list;
    }

    /**
     * A method handling a delete action event of a already stored diagnosis
     * within the list of diagnoses.
     *
     * @param event an action event.
     */
    public void delete(ActionEvent event) {
        list.remove(selectedDiagnosis);
    }

    /**
     * A method returning if the diagnoses list is empty.
     *
     * @return if the list of diagnoses is empty.
     */
    public boolean isEmpty() {
        return list.isEmpty();
    }

    /**
     * A method cleaning the list of diagnoses.
     */
    public void clear() {
        //Unselecting the curently selected diagnosis
        selectedDiagnosis = null;

        //Getting the list iterator
        Iterator<Diagnosis> it = list.iterator();

        //Iterating through the list of stored diagnoses
        while (it.hasNext()) {
            //Removing the next stored diagnosis
            it.next();
            it.remove();
        }
    }
}

src/main/java/com/gnomon/epsos/model/DocumentExt.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gnomon.epsos.model;

import java.util.List;

/**
 *
 * @author kostaskarkaletsis
 */
public class DocumentExt {

    private Patient patient;
    private List<PatientDocument> documents;

    public Patient getPatient() {
        return patient;
    }

    public void setPatient(Patient patient) {
        this.patient = patient;
    }

    public List<PatientDocument> getDocuments() {
        return documents;
    }

    public void setDocuments(List<PatientDocument> documents) {
        this.documents = documents;
    }

}

src/main/java/com/gnomon/epsos/model/EpsosDocument.java
package com.gnomon.epsos.model;

import java.util.Calendar;

public class EpsosDocument {

        private String docId;
	private String author;
	private String description;
	private Calendar creationDate;
	private String title;		
	
	public EpsosDocument() {
		super();
	}
	public String getAuthor() {
		return author;
	}
	public void setAuthor(String author) {
		this.author = author;
	}
	public String getDescription() {
		return description;
	}
	public void setDescription(String description) {
		this.description = description;
	}
	public Calendar getCreationDate() {
		return creationDate;
	}
	public void setCreationDate(Calendar creationDate) {
		this.creationDate = creationDate;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}

        public String getDocId() {
            return docId;
        }

        public void setDocId(String docId) {
            this.docId = docId;
        }

	
	
	
}

src/main/java/com/gnomon/epsos/model/HcerBean.java
package com.gnomon.epsos.model;

import com.gnomon.LiferayUtils;
import com.gnomon.epsos.hcer.HCERDocs;
import com.gnomon.epsos.hcer.HcerPersistentManager;
import com.liferay.portal.model.User;
import java.io.Serializable;
import java.util.List;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import org.apache.commons.lang.exception.ExceptionUtils;
import org.apache.log4j.Logger;
import org.orm.PersistentException;
import org.orm.PersistentSession;

@ManagedBean
@ViewScoped
public class HcerBean implements Serializable {

    /**
     *
     */
    private static final long serialVersionUID = 1L;
    private List<HCERDocs> docs;
    private static final Logger log = Logger.getLogger("HcerBean");

    public HcerBean() throws PersistentException {
        log.info("quering hcer docs");
        User user = LiferayUtils.getPortalUser();
        LiferayUtils.storeToSession("user", user);
        PersistentSession s = HcerPersistentManager.instance().getSession();
        try {
            docs = HCERDocs.queryHCERDocs(null, "creationDate desc");
            log.info(docs.size());
        } catch (PersistentException ex) {
            log.error(ExceptionUtils.getStackTrace(ex));
        } finally {
            s.close();
        }
    }

    public List<HCERDocs> getDocs() {
        return docs;
    }

    public void setDocs(List<HCERDocs> docs) {
        this.docs = docs;
    }

}

src/main/java/com/gnomon/epsos/model/Identifier.java
package com.gnomon.epsos.model;

public class Identifier {

    private String key;
    private String domain;
    private String userValue;
    private String friendlyName;

    public Identifier() {

    }

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public String getDomain() {
        return domain;
    }

    public void setDomain(String domain) {
        this.domain = domain;
    }

    public String getUserValue() {
        return userValue;
    }

    public void setUserValue(String userValue) {
        this.userValue = userValue;
    }

	public String getFriendlyName() {
		return friendlyName;
	}

	public void setFriendlyName(String friendlyName) {
		this.friendlyName = friendlyName;
	}


}

src/main/java/com/gnomon/epsos/model/MyBean.java
package com.gnomon.epsos.model;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;
import javax.portlet.RenderRequest;
import javax.xml.parsers.DocumentBuilder;
import javax.xml.parsers.DocumentBuilderFactory;

import org.apache.log4j.Logger;
import org.hibernate.exception.ExceptionUtils;
import org.joda.time.DateTime;
import org.opensaml.DefaultBootstrap;
import org.opensaml.saml2.core.Assertion;
import org.opensaml.xml.Configuration;
import org.opensaml.xml.io.Unmarshaller;
import org.opensaml.xml.io.UnmarshallerFactory;
import org.opensaml.xml.parse.BasicParserPool;
import org.primefaces.model.StreamedContent;
import org.w3c.dom.Document;
import org.w3c.dom.Element;

import tr.com.srdc.epsos.util.Constants;

import com.gnomon.LiferayUtils;
import com.gnomon.epsos.FacesService;
import com.gnomon.epsos.MyServletContextListener;
import com.gnomon.epsos.service.ConsentException;
import com.gnomon.epsos.service.Demographics;
import com.gnomon.epsos.service.EpsosHelperService;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.PropsUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.model.User;

import epsos.ccd.gnomon.auditmanager.EventOutcomeIndicator;
import epsos.openncp.protocolterminator.ClientConnectorConsumer;
import epsos.openncp.protocolterminator.clientconnector.EpsosDocument1;
import epsos.openncp.protocolterminator.clientconnector.GenericDocumentCode;
import epsos.openncp.protocolterminator.clientconnector.PatientDemographics;
import epsos.openncp.protocolterminator.clientconnector.PatientId;
import epsos.openncp.protocolterminator.clientconnector.SubmitDocumentResponse;
import eu.epsos.util.EvidenceUtils;
import eu.epsos.util.IheConstants;

@ManagedBean
@SessionScoped
public class MyBean implements Serializable {

	private static final long serialVersionUID = 1L;
	private List<Country> countries;
	private String selectedCountry;
	private List<Identifier> identifiers;
	private List<Demographics> demographics;
	private List<Patient> patients;

	@ManagedProperty(value = "#{selectedPatient}")
	private Patient selectedPatient;
	private List<PatientDocument> patientDocuments;
	private PatientDocument selectedDocument;
	private EpsosDocument selectedEpsosDocument;
	private String documentHtml;
	private List<PatientDocument> patientPrescriptions;
	private String prescriptionHtml;
	private boolean showDemographics;
	private boolean showPatientList = true;
	private StreamedContent prescriptionFile;
	private PatientDocument selectedPrescriptionFile;
	private Assertion hcpAssertion = null;
	private boolean trcassertionexists = false;
	private boolean trcassertionnotexists = true;
	private Assertion trcAssertion;
	private Date consentStartDate;
	private Date consentEndDate;
	private String consentOpt;
	private String purposeOfUse;
	private String purposeOfUseForPS;
	private String purposeOfUseForEP;
	private String queryPatientsException;
	private String queryDocumentsException;
	private String queryPrescriptionsException;
	private boolean showEP;
	private boolean showPS;
	private boolean showMRO;
	private boolean enableMRO;
	private boolean enableHCER;
	private boolean enableCCD;
	private boolean enableCONSENT;
	private boolean enablePatientDocuments;
	private boolean enablePrescriptionDocuments;
	private boolean canConvert;
	private boolean consentExists;
	private String errorUserAssertion;
	private String cdaStylesheet;
	private String signedTRC;
	private static final Logger log = Logger.getLogger("MyBean");

	public MyBean() {
		log.info("Initializing MyBean ...");
		checkButtonPermissions();
		String epsosPropsPath = System.getenv("EPSOS_PROPS_PATH");
		log.info("EPSOS PROPS PATH IS : " + epsosPropsPath);
		if (!Validator.isNull(epsosPropsPath)) {
			try {
				cdaStylesheet = EpsosHelperService
						.getConfigProperty(EpsosHelperService.PORTAL_CDA_STYLESHEET);
				consentExists = false;
				consentOpt = "1";
				countries = new ArrayList<Country>();
				identifiers = new ArrayList<Identifier>();
				demographics = new ArrayList<Demographics>();
				countries = EpsosHelperService.getCountriesFromCS(LiferayUtils
						.getPortalLanguage());
				log.info("Countries found : " + countries.size());
			} catch (Exception e) {
				FacesContext.getCurrentInstance().addMessage(
						null,
						new FacesMessage(FacesMessage.SEVERITY_ERROR,
								"Error getting user", ""));
				log.error("Error getting user");
				log.error(ExceptionUtils.getStackTrace(e));
			}
		} else {
			FacesContext.getCurrentInstance().addMessage(
					null,
					new FacesMessage(FacesMessage.SEVERITY_ERROR,
							"EPSOS_PROPS_PATH not found", ""));
		}
	}

	public void showPrescription(ActionEvent actionEvent)
			throws SystemException {
		RenderRequest renderRequest = (RenderRequest) (FacesContext
				.getCurrentInstance().getExternalContext().getRequestMap()
				.get("javax.portlet.request"));
		String parameter = renderRequest.getParameter("productId");
		log.info("PRODUCT ID: " + parameter);
	}

	public List<Country> getCountries() {
		return countries;
	}

	public String getSelectedCountry() {
		return selectedCountry;
	}

	public void setSelectedCountry(String selectedCountry) {

		User user = LiferayUtils.getPortalUser();
		LiferayUtils.storeToSession("user", user);

		this.selectedCountry = selectedCountry;
		identifiers = EpsosHelperService.getCountryIdentifiers(
				this.selectedCountry, LiferayUtils.getPortalLanguage(), null,
				null);
		demographics = EpsosHelperService.getCountryDemographics(
				this.selectedCountry, LiferayUtils.getPortalLanguage(), null,
				null);

		showDemographics = !demographics.isEmpty();
		LiferayUtils.storeToSession("selectedCountry", selectedCountry);
		patients = new ArrayList<Patient>();
	}

	public boolean getAssertionExists() {
		if (trcassertionexists) {
			return (true);
		} else {
			return (false);
		}
	}

	public boolean getAssertionNotExists() {
		if (!trcassertionexists) {
			return (true);
		} else {
			return (false);
		}
	}

	public void searchPatientsRequest(ActionEvent event) {
		checkButtonPermissions();
		log.info("searchPatientORequest ::: Selected country is : "
				+ selectedCountry);
		String country = (String) event.getComponent().getAttributes()
				.get("selectedCountry");
		identifiers = (List<Identifier>) event.getComponent().getAttributes()
				.get("identifiers");
		demographics = (List<Demographics>) event.getComponent()
				.getAttributes().get("demographics");
		if (Validator.isNotNull(country)) {
			selectedCountry = country;
		}
		log.info("searchPatientsRequest ::: Selected country is : "
				+ selectedCountry);
		searchPatients();
	}

	private void searchPatients(Assertion assertion, List<Identifier> id_,
			List<Demographics> dem_, String country) {
		log.info("Search Patients selected country is: " + country);
		String runningMode = MyServletContextListener.getRunningMode();
		String strMsg = "";
		Assertion ass = null;
		if (runningMode.equals("demo")) {
			patients = EpsosHelperService.getMockPatients();
			trcAssertion = null;
			trcassertionnotexists = true;
			trcassertionexists = false;
			showPatientList = true;
		} else {
			try {
				trcAssertion = null;
				trcassertionnotexists = true;
				trcassertionexists = false;
				patients = new ArrayList<Patient>();
				String serviceUrl = EpsosHelperService
						.getConfigProperty(EpsosHelperService.PORTAL_CLIENT_CONNECTOR_URL);
				log.info("CONNECTOR URL IS: " + serviceUrl);

				PatientDemographics pd = EpsosHelperService
						.createPatientDemographicsForQuery(id_, dem_);

				ClientConnectorConsumer proxy = MyServletContextListener
						.getClientConnectorConsumer();// new
														// ClientConnectorConsumer(serviceUrl);
				log.info("Test Assertions: "
						+ EpsosHelperService
								.getConfigProperty(EpsosHelperService.PORTAL_TEST_ASSERTIONS));
				ass = assertion;

				log.info("Searching for patients in " + country);
				log.info("Assertion id: " + ass.getID());
				log.info("PD: " + pd.toString());
				strMsg = pd.toString();

				try {
					EvidenceUtils.createEvidenceREMNRO(strMsg, "NI_PD",
							new DateTime(), EventOutcomeIndicator.FULL_SUCCESS
									.getCode().toString(), "NI_PD_REQ", ass
									.getID());
				} catch (Exception e) {
					log.error(ExceptionUtils.getStackTrace(e));
				}

				List<PatientDemographics> queryPatient = proxy.queryPatient(
						ass, country, pd);

				try {
					EvidenceUtils.createEvidenceREMNRR(strMsg, "NI_PD",
							new DateTime(), EventOutcomeIndicator.FULL_SUCCESS
									.getCode().toString(), "NI_PD_RES_SUCC",
							ass.getID());
				} catch (Exception e) {
					log.error(ExceptionUtils.getStackTrace(e));
				}

				for (PatientDemographics aux : queryPatient) {
					Patient patient = EpsosHelperService.populatePatient(aux);
					patients.add(patient);
					queryPatientsException = "";
				}
				if (queryPatient.isEmpty()) {
					queryPatientsException = LiferayUtils
							.getPortalTranslation("patient.list.no.patient");
				}
				log.info("Found " + patients.size() + " patients");
				showPatientList = true;
			} catch (Exception ex) {

				try {

src/main/java/com/gnomon/epsos/model/adapter/DateAdapter.java
package com.gnomon.epsos.model.adapter;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.xml.bind.annotation.adapters.XmlAdapter;

public class DateAdapter extends XmlAdapter<String, Date> {

    private SimpleDateFormat dateFormat = new SimpleDateFormat("yyyyMMdd");

    @Override
    public String marshal(Date v) throws Exception {
        return dateFormat.format(v);
    }

    @Override
    public Date unmarshal(String v) throws Exception {
        return dateFormat.parse(v);
    }

}

src/main/webapp/viewOptions.xhtml
<!DOCTYPE html PUBLIC "-W3CDTD XHTML 1.0 TransitionalEN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	xmlns:c="http://java.sun.com/jsp/jstl/core">
<h:head>
</h:head>
<body>

	<f:view locale="#{facesContext.externalContext.requestLocale}" />

	<p:ajaxStatus style="width:16px;height:16px;" id="ajaxStatusPanel">
		<f:facet name="start">
			<h:graphicImage value="/images/loading.gif"
				style="text-align:center;width:40px;height:40px;" />
		</f:facet>
		<f:facet name="complete">
			<h:outputText value="" />
		</f:facet>
	</p:ajaxStatus>
	<BR />

	<h:form>
		<p:messages id="messages" showDetail="true" autoUpdate="true" closable="true" />  
		<p:commandLink ajax="false"
			action="/view.xhtml?javax.portlet.faces.PortletMode=view&amp;javax.portlet.faces.WindowState=normal">
			<p:graphicImage value="/images/Home-Button.png" />
		</p:commandLink>
		<p:graphicImage value="/images/flags/#{myBean.selectedCountry}.png"
			style="text-align:center;width:30px;height:30px;" />
	</h:form>

		<p:panel header="#{msg['navi.report.summary']}">
			<table>
				<tr>
					<td><b><h:outputText value="#{msg['patient.data.givenname']}" /></b></td>
					<td>&nbsp;</td>
					<td><h:outputText value="#{myBean.selectedPatient.name}" /></td>
				</tr>
				<tr>
					<td><b><h:outputText value="#{msg['patient.data.surname']}" /></b></td>
					<td>&nbsp;</td>
					<td><h:outputText value="#{myBean.selectedPatient.familyName}" /></td>
				</tr>
				<tr>
					<td><b><h:outputText value="#{msg['patient.data.street.address']}" /></b></td>
					<td>&nbsp;</td>
					<td><h:outputText value="#{myBean.selectedPatient.address}" /></td>
				</tr>
				<tr>
					<td><b><h:outputText value="#{msg['patient.data.code']}" /></b></td>
					<td>&nbsp;</td>
					<td><h:outputText value="#{myBean.selectedPatient.postalCode}" /></td>
				</tr>
				<tr>
					<td><b><h:outputText value="#{msg['patient.data.city']}" /></b></td>
					<td>&nbsp;</td>
					<td><h:outputText value="#{myBean.selectedPatient.city}" /></td>
				</tr>
				<tr>
					<td><b><h:outputText value="#{msg['patient.data.country']}" /></b></td>
					<td>&nbsp;</td>
					<td><h:outputText value="#{myBean.selectedPatient.country}" /></td>
				</tr>
			</table>
		</p:panel>
        
                            <p:commandLink
                                    action="/viewPatientConfirmationForAll.xhtml?javax.portlet.faces.PortletMode=view&amp;javax.portlet.faces.WindowState=normal"
                                    id="pall"
                                    ajax="false"
                                    title="#{msg['navi.report.summary']}"
                                    rendered="#{myBean.assertionNotExists}"
                                    disabled="#{!myBean.enablePatientDocuments}">
                                    <f:setPropertyActionListener value="#{patient}"
                                            target="#{myBean.selectedPatient}" />
                                    #{msg['ui.confirmation.give']}

                            </p:commandLink>                              
                              
                            <p:commandLink
                                    action="/viewPatientConfirmationForDocuments.xhtml?javax.portlet.faces.PortletMode=view&amp;javax.portlet.faces.WindowState=normal"
                                    id="p1"
                                    ajax="false"
                                    title="#{msg['navi.report.summary']}"
                                    rendered="#{myBean.assertionNotExists}"
                                    disabled="#{!myBean.enablePatientDocuments}">
                                    <f:setPropertyActionListener value="#{patient}"
                                            target="#{myBean.selectedPatient}" />
                                    #{msg['ui.ps.info']}

                            </p:commandLink>

                            <p:commandLink
                                    action="/viewDocuments.xhtml?javax.portlet.faces.PortletMode=view&amp;javax.portlet.faces.WindowState=normal"
                                    id="p2"
                                    ajax="false"
                                    title="#{msg['navi.report.summary']}"
                                    rendered="#{myBean.assertionExists}"
                                    disabled="#{!myBean.enablePatientDocuments}">
                                    <f:setPropertyActionListener value="#{patient}"
                                            target="#{myBean.selectedPatient}" />
                                    #{msg['ui.ps.info']}
                            </p:commandLink>

                            <p:commandLink 
                                    action="/viewPrescriptions.xhtml?javax.portlet.faces.PortletMode=view&amp;javax.portlet.faces.WindowState=normal"
                                    ajax="false"
                                    id="p3"
                                    title="#{msg['navi.report.prescription']}"
                                    rendered="#{myBean.assertionExists and myBean.enablePrescriptionDocuments}"
                                    disabled="#{!myBean.enablePrescriptionDocuments}">
                                    <f:setPropertyActionListener value="#{patient}"
                                            target="#{myBean.selectedPatient}" />
                                    #{msg['ui.ep.info']}
                            </p:commandLink>

                            <p:commandLink 
                                    action="/viewPatientConfirmation.xhtml?javax.portlet.faces.PortletMode=view&amp;javax.portlet.faces.WindowState=normal"
                                    ajax="false"
                                    id="p4"
                                    title="#{msg['navi.report.prescription']}"
                                    rendered="#{myBean.assertionExists and myBean.enablePrescriptionDocuments}"
                                    disabled="#{!myBean.enablePrescriptionDocuments}">
                                    <f:setPropertyActionListener value="#{patient}"
                                            target="#{myBean.selectedPatient}" />
                                    #{msg['ui.ep.info']}
                            </p:commandLink>

                            <p:commandLink 
                                    action="/viewConsent.xhtml?javax.portlet.faces.PortletMode=view&amp;javax.portlet.faces.WindowState=normal"
                                    ajax="false"
                                    id="p5"
                                    title="#{msg['patient.data.agreement.title']}"
                                    rendered="#{myBean.enableCONSENT}"
                                    disabled="#{!myBean.enablePatientDocuments}">
                                    <f:setPropertyActionListener value="#{patient}"
                                            target="#{myBean.selectedPatient}" />
                                    #{msg['ui.consent.info']}
                            </p:commandLink>

                            <p:commandLink 
                                    action="/viewPatientConfirmationForConsent.xhtml?javax.portlet.faces.PortletMode=view&amp;javax.portlet.faces.WindowState=normal"
                                    ajax="false"
                                    id="p6"
                                    title="#{msg['patient.data.agreement.title']}"
                                    rendered="#{myBean.assertionNotExists and myBean.enableCONSENT}"
                                    disabled="#{!myBean.enablePatientDocuments}">
                                    <f:setPropertyActionListener value="#{patient}"
                                            target="#{myBean.selectedPatient}" />
                                    #{msg['ui.consent.info']}
                            </p:commandLink>

                            <p:commandLink 
                                action="/viewHCER.xhtml?javax.portlet.faces.PortletMode=view&amp;javax.portlet.faces.WindowState=normal"
                                id="p7"
                                ajax="false" 
                                title="#{msg['patient.data.hcer.title']}"
                                rendered="#{myBean.assertionExists and myBean.enableHCER}"
                                disabled="#{!myBean.enableHCER}">
                                <f:setPropertyActionListener value="#{patient}"
                                                             target="#{myBean.selectedPatient}" />
                                    #{msg['ui.hcer.info']}
                            </p:commandLink>
                            <p:commandLink 
                                action="/viewPatientConfirmationForHCER.xhtml?javax.portlet.faces.PortletMode=view&amp;javax.portlet.faces.WindowState=normal"
                                ajax="false"
                                id="p8"
                                title="#{msg['patient.data.hcer.title']}"
                                rendered="#{myBean.assertionNotExists and myBean.enableHCER}"
                                disabled="#{!myBean.enableHCER}">
                                <f:setPropertyActionListener value="#{patient}"
                                                             target="#{myBean.selectedPatient}" />
                                    #{msg['ui.hcer.info']}
                            </p:commandLink>

                            <p:commandLink 
                                action="/viewMRO.xhtml?javax.portlet.faces.PortletMode=view&amp;javax.portlet.faces.WindowState=normal"
                                ajax="false"
                                id="p9"
                                title="#{msg['patient.data.mro.title']}"
                                rendered="#{myBean.assertionExists and myBean.enableMRO}"
                                disabled="#{!myBean.enableMRO}">
                                <f:setPropertyActionListener value="#{patient}"
                                                             target="#{myBean.selectedPatient}" />
                                    #{msg['ui.mro.info']}
                            </p:commandLink>
                            <p:commandLink 
                                action="/viewPatientConfirmationForMRO.xhtml?javax.portlet.faces.PortletMode=view&amp;javax.portlet.faces.WindowState=normal"
                                ajax="false"
                                id="p10"
                                title="#{msg['patient.data.mro.title']}"
                                rendered="#{myBean.assertionNotExists and myBean.enableMRO}"
                                disabled="#{!myBean.enableMRO}">
                                <f:setPropertyActionListener value="#{patient}"
                                                             target="#{myBean.selectedPatient}" />
                                    #{msg['ui.mro.info']}
                            </p:commandLink>                              
                        </ui:repeat>  
                    </p:panel>
	</h:form>
</body>
</html>